---
- name: Prepare Openshift dependencies
  hosts: all
  gather_facts: no

  roles:
    - openshift


- name: Terraform Section
  hosts: all
  gather_facts: no
  become: yes

  tags: terraform
  tasks:
    - name: Read in master ignition file
      slurp:
        src: '/root/openshift/{{cluster_id}}/master.ign'
      register: master_ignition

    - name: Debug master ignition variable
      debug:
        msg: "{{ master_ignition['content'] | b64decode }}"

    - name: Read in worker ignition file
      slurp:
        src: '/root/openshift/{{cluster_id}}/worker.ign'
      register: worker_ignition

    - name: create Terraform configuration file
      template:
        src: terraform.tfvars.j2
        dest: ~/openshift/installer/upi/vsphere/terraform.tfvars

    - name: Remove previous terraform files
      file:
        path: '/root/openshift/installer/upi/vsphere/terraform.tfstate'
        state: absent
    - name: Remove previous terraform hidden directory
      file:
        path: '/root/openshift/installer/upi/vsphere/.terraform'
        state: absent
    - name: Terraform init
      command: >
        chdir=/root/openshift/installer/upi/vsphere terraform init
    #- name: Terraform Apply
    #  command: >
    #    chdir=/root/openshift/installer/upi/vsphere terraform apply --auto-approve
