---
- name: Prepare Openshift dependencies
  hosts: all
  gather_facts: no

  roles:
    - openshift


- name: Terraform Section
  hosts: all
  gather_facts: no
  become: yes
  #vars:
  #  #master_ignition: "{{lookup('file', '/root/openshift/ocp4/master.ign')}}"
  #  worker_ignition: "{{lookup('file', '/root/openshift/ocp4/worker.ign')}}"
  tags: terraform
  tasks:
    - name: Read in master ignition file
      slurp:
        src: '/root/openshift/ocp4/master.ign'
      register: master_ignition
    - name: Read in worker ignition file
      slurp:
        src: '/root/openshift/ocp4/worker.ign'
      register: worker_ignition

    - name: Debug variables
      debug: var={{master_ignition}}

    - name: create Terraform configuration file
      template:
        src: terraform.tfvars.j2
        dest: ~/openshift/installer/upi/vsphere/terraform.tfvars
