---
- name: Prepare Openshift dependencies
  hosts: all
  gather_facts: no

  roles:
    - openshift


- name: Terraform Section
  hosts: all
  gather_facts: no
  vars:
    master_ignition: "{{lookup('file', /root/openshift/ocp4/master.ign')}}"
    worker_ignition: "{{lookup('file', /root/openshift/ocp4/worker.ign')}}"
  tasks:
    - name: create Terraform configuration file
      template:
        src: terraform.tfvars.j2
        dest: ~/opentshift/installer/upi/vsphere/terrafrom.tfvars
