
- name: Delete configuration directory
  file:
    path: ~/openshift/{{cluster_id}}
    state: absent

- name: Recreate configuration directory
  file:
    path: ~/openshift/{{cluster_id}}
    state: directory

- name: Template ignition configuration file
  template:
    src: install-config.yaml.j2
    dest: ~/openshift/{{cluster_id}}/install-config.yaml

- name: Create ignition files
  command: >
    openshift-install --dir ~/openshift/{{cluster_id}} create ignition-configs

#- name: Copy bootstrap ignition file to web server
#  copy:
#    src: ~/openshift/{{cluster_id}}/bootstrap.ign

- name: Copy bootstrap ignition file to web server
  command: >
    scp ~/openshift/{{cluster_id}}/bootstrap.ign {{nfs_username}}@{{nfs_server}}:/volume1/web/openshift/bootstrap.ign

#- name: Terraform Section
#  hosts: all
#  gather_facts: no
#  vars:
#    master_ignition: "{{lookup('file', /root/openshift/ocp4/master.ign')}}"
#    worker_ignition: "{{lookup('file', /root/openshift/ocp4/worker.ign')}}"
#  tasks:
#
#    - name: create Terraform configuration file
#      template:
#        src: terraform.tfvars.j2
#        dest: ~/opentshift/installer/upi/vsphere/terrafrom.tfvars
