
- name: Delete configuration directory
  file:
    path: /root/openshift/ocp4
    state: absent

- name: Recreate configuration directory
  file:
    path: /root/openshift/ocp4
    state: directory

- name: Template ignition configuration file
  template:
    src: install-config.yaml.j2
    dest: /root/openshift/ocp4/install-config.yaml

- name: Create ignition files
  command: >
    openshift-install --dir ~/openshift/{{cluster_id}} create ignition-configs

#- name: Copy bootstrap ignition file to web server
#  copy:
#    src: ~/openshift/{{cluster_id}}/bootstrap.ign
